SELECT  F1.F1_FILIAL
	   ,F1.F1_EMISSAO
	   ,F1.F1_DOC
	   ,A2.A2_CGC
	   ,F1.F1_FORNECE 
	   ,F1.F1_LOJA 
	   ,D1.D1_TOTAL
	   ,D1.D1_TES
	   ,D1.D1_CF
	   ,CASE WHEN F1.F1_XSETOR  = '1' THEN 'VEICULOS'
			 WHEN F1.F1_XSETOR  = '2' THEN 'OFICINA'
			 WHEN F1.F1_XSETOR  = '3' THEN 'BALCAO'
			 WHEN F1.F1_XSETOR  = ''  THEN 'SEMREGISTRO' 
		END AS F1_XSETOR
	 

FROM SF1010 AS F1
INNER JOIN SD1010 AS D1
ON  F1.F1_FILIAL = D1.D1_FILIAL
AND F1.F1_DOC = D1.D1_DOC
AND F1.F1_SERIE = D1.D1_SERIE
AND F1.F1_FORNECE = D1.D1_FORNECE
AND F1.F1_LOJA = D1.D1_LOJA
AND F1.D_E_L_E_T_ = ''
AND D1.D_E_L_E_T_ = ''
INNER JOIN SA2010 AS A2
ON  A2.A2_COD = F1.F1_FORNECE
AND A2.A2_LOJA = F1.F1_LOJA
AND A2.D_E_L_E_T_ = ''
AND A2.A2_MSBLQL = '2'

WHERE F1.F1_FILIAL BETWEEN '' AND 'ZZZZZZ'
AND  F1.F1_DOC  BETWEEN '' AND 'ZZZZZZZZZ'
AND F1.F1_EMISSAO BETWEEN '' AND 'ZZZZZZZZ'
AND F1.F1_XSETOR IN ('1','2','3','')
ORDER BY F1_EMISSAO