--ORDEM DE SERVIÇOS
SELECT DISTINCT 
	 VO1.VO1_FILIAL AS FILIAL
	,VO1.VO1_NUMOSV AS NUMOSV
	,VO3.VO3_CODITE AS CODPEC
	,VO3.VO3_VALPEC AS VALPECAS
	,VO4.VO4_CODSER AS CODSRV
	,VO4.VO4_VALVEN AS VALSERV
	,CASE WHEN VO1.VO1_STATUS = 'A' THEN 'Aberta'
		  WHEN VO1.VO1_STATUS = 'D' THEN 'Liberada'
	 END AS STATUS_OS
	,VO1.VO1_DATABE AS DT_ABERTURA

FROM VO1010 AS VO1
LEFT JOIN VO3010 AS VO3
ON VO3.VO3_NUMOSV = VO1.VO1_NUMOSV
AND VO3.D_E_L_E_T_ = ''
LEFT JOIN VO4010 AS VO4
ON VO4.VO4_NUMOSV = VO1.VO1_NUMOSV
AND VO4.D_E_L_E_T_ = '' 

WHERE VO1.D_E_L_E_T_ = ''
AND VO1_STATUS IN  ('A','D')
AND VO4.VO4_VALVEN >= 0



